language: node_js

node_js:
- "11"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - pushd back && yarn install && popd
  - pushd front && yarn install && popd

script:
  - pushd back
  - yarn lint
  - yarn coveralls
  - popd
  - pushd front
  - yarn lint
  - yarn test
  - yarn coveralls
  - if [ $TRAVIS_BRANCH == 'master' ]; then yarn build && mv build ../; fi
  - popd

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

notifications:
  email:
    recipients:
      - leandro.jdl@gmail.com
      - juannpm159@gmail.com
      - facundokhalil@gmail.com
    on_success: change
    on_failure: change
