language: node_js

node_js:
- "11"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - cd front && yarn install

script:
  - yarn lint
  - yarn test
  - yarn build
  - mv build ../

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdes-tp-anonymous/build
  on:
    branch: testing-travis-deploy

notifications:
  email:
    recipients:
      - leandro.jdl@gmail.com
      - juannpm159@gmail.com
      - facundokhalil@gmail.com
    on_success: change
    on_failure: change
