language: node_js

node_js:
- "11"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - pushd .travis
  - openssl aes-256-cbc -K $encrypted_160c63935393_key -iv $encrypted_160c63935393_iv -in deploy_key_pdes.enc -out deploy_key_pdes -d
  - rm deploy_key_pdes.enc
  - chmod 600 deploy_key_pdes
  - mv deploy_key_pdes ~/.ssh/id_rsa
  - popd

before_script:
  - mkdir .lcov
  - pushd back && yarn install && popd
  - pushd front && yarn install && popd

script:
  - pushd back
  - yarn lint
  - yarn coverage
  - popd
  - pushd front
  - yarn lint
  - yarn coverage
  - if [ $TRAVIS_BRANCH == 'master' ]; then yarn build && mv build ../; fi
  - popd

after_script:
  - pushd back
  - yarn coveralls
  - popd
  - rm -rf .lcov

after_success:
  - bash .travis/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

notifications:
  email:
    recipients:
      - leandro.jdl@gmail.com
      - juannpm159@gmail.com
      - facundokhalil@gmail.com
    on_success: change
    on_failure: change
