version: '2'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - '127.0.0.1:8081:8081'
  api:
    image: pdesanonymous/api
    restart: always
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
      - mongo-express
  web:
    image: pdesanonymous/web
    restart: always
    depends_on:
      - api
    ports:
      - '127.0.0.1:8000:80'
