language: node_js

node_js:
- "11"

script:
  - "cd front"
  - "yarn lint"
  - "yarn test"
  - "cd .."

notifications:
  email:
    recipients:
      - leandro.jdl@gmail.com
      - juannpm159@gmail.com
      - facundokhalil@gmail.com
    on_success: change
    on_failure: change
